# Config file for training the model

# Chemins vers les datasets
data:
  train_data: "data/train"
  val_data: "data/validation"
  test_data: "data/test"

# Hyperparamètres pour l'entraînement
training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10
  optimizer: "Adam"  # Optimiseur
  loss_function: "CrossEntropyLoss"  # Fonction de perte

# Paramètres du modèle
model:
  architecture: "ResNet18"  # Architecture du modèle
  pretrained: true  # Si le modèle est pré-entraîné
  num_classes: 2  # Nombre de classes (par exemple, cancer vs non-cancer)

# Options d’évaluation
evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
  confusion_matrix: true  # Calculer la matrice de confusion ?

# Option de sauvegarde
save_model:
  save_path: "models/trained_model.pth"
  save_frequency: 5  # Sauvegarde du modèle tous les 5 epochs
